language: csharp
solution: TransbankSDK.sln
mono: none
dotnet: 1.1.5
env: DOTNETCORE=1
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "transbankdevelopers"
    token:
      secure: "TcVF7jxZcI3mgRSeDKjeZtFMtSDJCiznQjGf7JP60lGfHwLB8kxPEymP0Jmf3ndDbfteQOU1p08yb9OxNFWy3Ba6zuScboT4SQa2fWp7j3c7j2fqJA+MT+v01fx6hUufnNThpoxD1ziq/vrklp5Mhf0RcolE4p5FSeSjfSWvtDP7UM3O5YJcxEx8hjdNPU0Eq0tyNfZnL13rIQ7q+GEL1/gmk3DzlhuGgCj7CmLqtP4DO9Jr0ICjg1iiVq8t7DKexreVhxj7FMA2j7l01vAhsEWV8kDF2sPx0Dq3K5HT0nDU9SaC1WerFri5f2jSyDVodhhjTaCxNXQ/Zpk5HcnuXKixRKs2Y2qFrBQmK2jATv1p/Ttkc99RzNvki4VpCh13ZCSmwekoh8Weq0AI1+yniHu7yv8NCkBDV0G8JgpM4n5ulFdjiaEw8POKvLbFZe6zKgdaOWYFEwlWFEI3rxbXQNJ91gQ8twWkgZERxZsFYDju6KFi2SdI7ZmVoTfUOceWuD4lDRghedljUkX7+7yLgPC7EQOE3N8MAgpueduigpXV4XFQX5PkSd4hWoxuxuZ5zFpZs5T9NaUp2YXfzi3yTB+YunZmF34omftp2ymXXd8aa9retpi0QjDe9hKJIR0rE6bFS8ppIHI8mnQ/aSmyMhjbPowQlZYbnJa7t5aCoFE="
script:
  - dotnet restore
  - dotnet build
  - cd TransbankTest
  - dotnet test
  - sonar-scanner