language: csharp
solution: TransbankSDK.sln
mono: none
dotnet: 2.0.3
addons:
  sonarcloud:
    organization: "transbankdevelopers"
    token:
      secure: "a1AzZUoJrWNOcT9NugHPtJJpX7Wx9RscIk0+nBZgy4IPhjJ+qbzEw7PHW4jMd0HduKri0igLQJJDSYLTwcyhYLTT8hGnhRRgxJbbdkUzOoO/oOMW3Nh0EyUtrVGAwUN7RoGVeOsJfsmS5xdp3RJdeVRoV4O3+3zIYXX3qk2bQkUQtXzufQPAAswvDny73NyVcpYmq82tg6JkZYMCKWssR9dlcN7qPdhHiTP5hqTz/lXkuAGapIzUzv/NNdfaFa4GRed6XxGOISUDqQxYUUpdBvT8JGAmF/gkHuypVvXrYTfow0hmahygoMm+6YG9TX8cueiRK0xVvDGTWzWfLEOxKmNmoLn11xo7Km4t68RZVUrE4+8KWEwhRiyE5tZWob1fEnidUqw2TLy0/25adw0J8n9GGCIuQuZ2O6bltRrC8gW8q0thyRcBoHw1JMzjGEE3eLT9iZzX5thclQ76jUFqwhbDh8/TWwH7vyAQ3IqmTJiXsMosZiqSaUYIpbIvaU3X5yczyCI2CU6KRpJwSsVMcIJTU6lJhVnk4t8u3k3hJykq4HT2sG5D2+F2SdWuFdNbT4j9G97DqwaVHxTIKTraQcsJq8dkwAWgE1TVwJ0vCvfd7xHzKZb2s6aobyt4EKLrB9X6Dg+HK+Tk4fQdFoVe3UgEqsPLsGO7V5orRXF9jFQ="
before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/mono-official.list
  - echo "Installing build tools..."
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y mono-complete unzip wget
  - echo "Install MSBuild Sonar scanner"
  - wget -O sonar.zip https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.0.2.892/sonar-scanner-msbuild-4.0.2.892.zip
  - mkdir -p tools/sonar
  - unzip -qq sonar.zip -d tools/sonar
  - ls -l tools/sonar
  - chmod +x tools/sonar/sonar-scanner-3.0.3.778/bin/sonar-scanner
  - pwd
script:
  - pwd
  - dotnet restore
  - mono tools/sonar/SonarQube.Scanner.MSBuild.exe begin /k:dotnetsdk /d:sonar.login=${SONAR_TOKEN} /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"
  - dotnet build
  - dotnet test TransbankTest --logger:trx
  - mono tools/sonar/SonarQube.Scanner.MSBuild.exe end /d:sonar.login=${SONAR_TOKEN}
  