version: 1.0.{build}
image: Visual Studio 2017
skip_branch_with_pr: true
cache:
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
before_deploy:
- ps: '.\scripts\appveyor-before-deploy.ps1'
deploy:
- provider: NuGet
  api_key:
    secure: 9FlFV3ckFidnwYpT8jOCAXI2wPn1yqkHpGl9l1AMRweR+bxjtCSmym/kXABTGxDX
  on:
    branch: 2.x

