version: 1.0.{build}
image: Visual Studio 2022
skip_branch_with_pr: true
cache:
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
before_deploy:
- ps: '.\scripts\appveyor-before-deploy.ps1'
deploy:
- provider: NuGet
  api_key:
    secure: xKHD+d8N8yuimk8KRQd78yJRsg6SAkdTnpNIMiaj5WjxVcTetr5DBEeqs/EpBxok
  on:
    branch: master

notifications:
- provider: Slack
  incoming_webhook:
    secure: FpjGXF6JUredzPLfH9xCxDsNFfC8RFIO5oKnRhVYydsWwQY6CaUaqCwSQJ9ZnANteb74/yaMt8BnXiLFn73NX9EhKr3AIjHZT2cJqEE1OKI=
  channel: transbank-github
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
