version: 1.0.{build}
image: Visual Studio 2017
skip_branch_with_pr: true
cache:
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
before_deploy:
- ps: '.\scripts\appveyor-before-deploy.ps1'
deploy:
- provider: NuGet
  api_key:
    secure: LeCi2XYIwTi/+V3LI/5jHJujW8AOW2T6x+/P5qswDJ94eBHqB0JbcrihanjI4434
  on:
    branch: master

notifications:
- provider: Slack
  incoming_webhook:
    secure: FpjGXF6JUredzPLfH9xCxDsNFfC8RFIO5oKnRhVYydsWwQY6CaUaqCwSQJ9ZnANt1e8J8c4T+b11QjTgRoN78jmo74TGBx9cCt3Y2mVHGnM=
  channel: transbank-continuum
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
