//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transbank.Webpay.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webpay3gint.transbank.cl:443/WSWebpayTransaction/cxf/WSCommerceIntegratio" +
            "nService")]
        public string Webpay_Transbank_Library_Wsdl_Capture_WSCommerceIntegrationServiceImplService {
            get {
                return ((string)(this["Webpay_Transbank_Library_Wsdl_Capture_WSCommerceIntegrationServiceImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webpay3gint.transbank.cl:443/WSWebpayTransaction/cxf/WSWebpayService")]
        public string Webpay_Transbank_Library_Wsdl_Normal_WSWebpayServiceImplService {
            get {
                return ((string)(this["Webpay_Transbank_Library_Wsdl_Normal_WSWebpayServiceImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webpay3gint.transbank.cl:443/WSWebpayTransaction/cxf/WSCommerceIntegratio" +
            "nService")]
        public string Webpay_Transbank_Library_Wsdl_Nullify_WSCommerceIntegrationServiceImplService {
            get {
                return ((string)(this["Webpay_Transbank_Library_Wsdl_Nullify_WSCommerceIntegrationServiceImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webpay3gint.transbank.cl:443/webpayserver/wswebpay/OneClickPaymentService" +
            "")]
        public string Webpay_Transbank_Library_Wsdl_OneClick_OneClickPaymentServiceImplService {
            get {
                return ((string)(this["Webpay_Transbank_Library_Wsdl_OneClick_OneClickPaymentServiceImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webpay3gint.transbank.cl:443/WSWebpayTransaction/cxf/WSCompleteWebpayServ" +
            "ice")]
        public string Webpay_Transbank_Library_Wsdl_Complete_WSCompleteWebpayServiceImplService {
            get {
                return ((string)(this["Webpay_Transbank_Library_Wsdl_Complete_WSCompleteWebpayServiceImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webpay3gint.transbank.cl:443/WSWebpayTransaction/cxf/WSWebpayService")]
        public string Webpay_Transbank_Library_Wsdl_Mall_Normal_WSWebpayServiceImplService {
            get {
                return ((string)(this["Webpay_Transbank_Library_Wsdl_Mall_Normal_WSWebpayServiceImplService"]));
            }
        }
    }
}
