//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace Transbank.Webpay.Wsdl.Complete.Certificacion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSCompleteWebpayServiceImplServiceSoapBinding", Namespace="http://service.wswebpay.webpay.transbank.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cardDetail))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(wsTransactionDetail))]
    public partial class WSCompleteWebpayServiceImplService : Microsoft.Web.Services3.WebServicesClientProtocol
    {
        
        private System.Threading.SendOrPostCallback acknowledgeCompleteTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback authorizeOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryShareOperationCompleted;
        
        private System.Threading.SendOrPostCallback initCompleteTransactionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSCompleteWebpayServiceImplService() {
            this.Url = global::Transbank.Webpay.Properties.Settings.Default.Webpay_Transbank_Library_Wsdl_Complete_Integracion_WSCompleteWebpayServiceImplService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event acknowledgeCompleteTransactionCompletedEventHandler acknowledgeCompleteTransactionCompleted;
        
        /// <remarks/>
        public event authorizeCompletedEventHandler authorizeCompleted;
        
        /// <remarks/>
        public event queryShareCompletedEventHandler queryShareCompleted;
        
        /// <remarks/>
        public event initCompleteTransactionCompletedEventHandler initCompleteTransactionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.wswebpay.webpay.transbank.com/", ResponseNamespace="http://service.wswebpay.webpay.transbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void acknowledgeCompleteTransaction([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tokenInput) {
            this.Invoke("acknowledgeCompleteTransaction", new object[] {
                        tokenInput});
        }
        
        /// <remarks/>
        public void acknowledgeCompleteTransactionAsync(string tokenInput) {
            this.acknowledgeCompleteTransactionAsync(tokenInput, null);
        }
        
        /// <remarks/>
        public void acknowledgeCompleteTransactionAsync(string tokenInput, object userState) {
            if ((this.acknowledgeCompleteTransactionOperationCompleted == null)) {
                this.acknowledgeCompleteTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnacknowledgeCompleteTransactionOperationCompleted);
            }
            this.InvokeAsync("acknowledgeCompleteTransaction", new object[] {
                        tokenInput}, this.acknowledgeCompleteTransactionOperationCompleted, userState);
        }
        
        private void OnacknowledgeCompleteTransactionOperationCompleted(object arg) {
            if ((this.acknowledgeCompleteTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.acknowledgeCompleteTransactionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.wswebpay.webpay.transbank.com/", ResponseNamespace="http://service.wswebpay.webpay.transbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsCompleteAuthorizeOutput authorize([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string token, [System.Xml.Serialization.XmlElementAttribute("paymentTypeList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] wsCompletePaymentTypeInput[] paymentTypeList) {
            object[] results = this.Invoke("authorize", new object[] {
                        token,
                        paymentTypeList});
            return ((wsCompleteAuthorizeOutput)(results[0]));
        }
        
        /// <remarks/>
        public void authorizeAsync(string token, wsCompletePaymentTypeInput[] paymentTypeList) {
            this.authorizeAsync(token, paymentTypeList, null);
        }
        
        /// <remarks/>
        public void authorizeAsync(string token, wsCompletePaymentTypeInput[] paymentTypeList, object userState) {
            if ((this.authorizeOperationCompleted == null)) {
                this.authorizeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthorizeOperationCompleted);
            }
            this.InvokeAsync("authorize", new object[] {
                        token,
                        paymentTypeList}, this.authorizeOperationCompleted, userState);
        }
        
        private void OnauthorizeOperationCompleted(object arg) {
            if ((this.authorizeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authorizeCompleted(this, new authorizeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.wswebpay.webpay.transbank.com/", ResponseNamespace="http://service.wswebpay.webpay.transbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsCompleteQuerySharesOutput queryShare([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string token, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string buyOrder, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int shareNumber) {
            object[] results = this.Invoke("queryShare", new object[] {
                        token,
                        buyOrder,
                        shareNumber});
            return ((wsCompleteQuerySharesOutput)(results[0]));
        }
        
        /// <remarks/>
        public void queryShareAsync(string token, string buyOrder, int shareNumber) {
            this.queryShareAsync(token, buyOrder, shareNumber, null);
        }
        
        /// <remarks/>
        public void queryShareAsync(string token, string buyOrder, int shareNumber, object userState) {
            if ((this.queryShareOperationCompleted == null)) {
                this.queryShareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryShareOperationCompleted);
            }
            this.InvokeAsync("queryShare", new object[] {
                        token,
                        buyOrder,
                        shareNumber}, this.queryShareOperationCompleted, userState);
        }
        
        private void OnqueryShareOperationCompleted(object arg) {
            if ((this.queryShareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryShareCompleted(this, new queryShareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.wswebpay.webpay.transbank.com/", ResponseNamespace="http://service.wswebpay.webpay.transbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsCompleteInitTransactionOutput initCompleteTransaction([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] wsCompleteInitTransactionInput wsCompleteInitTransactionInput) {
            object[] results = this.Invoke("initCompleteTransaction", new object[] {
                        wsCompleteInitTransactionInput});
            return ((wsCompleteInitTransactionOutput)(results[0]));
        }
        
        /// <remarks/>
        public void initCompleteTransactionAsync(wsCompleteInitTransactionInput wsCompleteInitTransactionInput) {
            this.initCompleteTransactionAsync(wsCompleteInitTransactionInput, null);
        }
        
        /// <remarks/>
        public void initCompleteTransactionAsync(wsCompleteInitTransactionInput wsCompleteInitTransactionInput, object userState) {
            if ((this.initCompleteTransactionOperationCompleted == null)) {
                this.initCompleteTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OninitCompleteTransactionOperationCompleted);
            }
            this.InvokeAsync("initCompleteTransaction", new object[] {
                        wsCompleteInitTransactionInput}, this.initCompleteTransactionOperationCompleted, userState);
        }
        
        private void OninitCompleteTransactionOperationCompleted(object arg) {
            if ((this.initCompleteTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.initCompleteTransactionCompleted(this, new initCompleteTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public partial class wsCompletePaymentTypeInput {
        
        private string commerceCodeField;
        
        private string buyOrderField;
        
        private wsCompleteQueryShareInput queryShareInputField;
        
        private bool gracePeriodField;
        
        private bool gracePeriodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string commerceCode {
            get {
                return this.commerceCodeField;
            }
            set {
                this.commerceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string buyOrder {
            get {
                return this.buyOrderField;
            }
            set {
                this.buyOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsCompleteQueryShareInput queryShareInput {
            get {
                return this.queryShareInputField;
            }
            set {
                this.queryShareInputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool gracePeriod {
            get {
                return this.gracePeriodField;
            }
            set {
                this.gracePeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gracePeriodSpecified {
            get {
                return this.gracePeriodFieldSpecified;
            }
            set {
                this.gracePeriodFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public partial class wsCompleteQueryShareInput {
        
        private long idQueryShareField;
        
        private int deferredPeriodIndexField;
        
        private bool deferredPeriodIndexFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idQueryShare {
            get {
                return this.idQueryShareField;
            }
            set {
                this.idQueryShareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int deferredPeriodIndex {
            get {
                return this.deferredPeriodIndexField;
            }
            set {
                this.deferredPeriodIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deferredPeriodIndexSpecified {
            get {
                return this.deferredPeriodIndexFieldSpecified;
            }
            set {
                this.deferredPeriodIndexFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public partial class wsCompleteInitTransactionOutput {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public partial class wsCompleteTransactionDetail {
        
        private decimal amountField;
        
        private string commerceCodeField;
        
        private string buyOrderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string commerceCode {
            get {
                return this.commerceCodeField;
            }
            set {
                this.commerceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string buyOrder {
            get {
                return this.buyOrderField;
            }
            set {
                this.buyOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(completeCardDetail))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public partial class cardDetail {
        
        private string cardNumberField;
        
        private string cardExpirationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cardExpirationDate {
            get {
                return this.cardExpirationDateField;
            }
            set {
                this.cardExpirationDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public partial class completeCardDetail : cardDetail {
        
        private int cvvField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cvv {
            get {
                return this.cvvField;
            }
            set {
                this.cvvField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public partial class wsCompleteInitTransactionInput {
        
        private wsCompleteTransactionType transactionTypeField;
        
        private string commerceIdField;
        
        private string buyOrderField;
        
        private string sessionIdField;
        
        private completeCardDetail cardDetailField;
        
        private wsCompleteTransactionDetail[] transactionDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsCompleteTransactionType transactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string commerceId {
            get {
                return this.commerceIdField;
            }
            set {
                this.commerceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string buyOrder {
            get {
                return this.buyOrderField;
            }
            set {
                this.buyOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public completeCardDetail cardDetail {
            get {
                return this.cardDetailField;
            }
            set {
                this.cardDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("transactionDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsCompleteTransactionDetail[] transactionDetails {
            get {
                return this.transactionDetailsField;
            }
            set {
                this.transactionDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public enum wsCompleteTransactionType {
        
        /// <remarks/>
        TR_COMPLETA_WS,
        
        /// <remarks/>
        TR_COMPLETA_MALL_WS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public partial class completeDeferredPeriod {
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private int periodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public partial class wsCompleteQuerySharesOutput {
        
        private string buyOrderField;
        
        private completeDeferredPeriod[] deferredPeriodsField;
        
        private long queryIdField;
        
        private decimal shareAmountField;
        
        private bool shareAmountFieldSpecified;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string buyOrder {
            get {
                return this.buyOrderField;
            }
            set {
                this.buyOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deferredPeriods", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public completeDeferredPeriod[] deferredPeriods {
            get {
                return this.deferredPeriodsField;
            }
            set {
                this.deferredPeriodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long queryId {
            get {
                return this.queryIdField;
            }
            set {
                this.queryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal shareAmount {
            get {
                return this.shareAmountField;
            }
            set {
                this.shareAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shareAmountSpecified {
            get {
                return this.shareAmountFieldSpecified;
            }
            set {
                this.shareAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(wsTransactionDetailOutput))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public partial class wsTransactionDetail {
        
        private decimal sharesAmountField;
        
        private bool sharesAmountFieldSpecified;
        
        private int sharesNumberField;
        
        private bool sharesNumberFieldSpecified;
        
        private decimal amountField;
        
        private string commerceCodeField;
        
        private string buyOrderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal sharesAmount {
            get {
                return this.sharesAmountField;
            }
            set {
                this.sharesAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sharesAmountSpecified {
            get {
                return this.sharesAmountFieldSpecified;
            }
            set {
                this.sharesAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sharesNumber {
            get {
                return this.sharesNumberField;
            }
            set {
                this.sharesNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sharesNumberSpecified {
            get {
                return this.sharesNumberFieldSpecified;
            }
            set {
                this.sharesNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string commerceCode {
            get {
                return this.commerceCodeField;
            }
            set {
                this.commerceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string buyOrder {
            get {
                return this.buyOrderField;
            }
            set {
                this.buyOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public partial class wsTransactionDetailOutput : wsTransactionDetail {
        
        private string authorizationCodeField;
        
        private string paymentTypeCodeField;
        
        private int responseCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string authorizationCode {
            get {
                return this.authorizationCodeField;
            }
            set {
                this.authorizationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paymentTypeCode {
            get {
                return this.paymentTypeCodeField;
            }
            set {
                this.paymentTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wswebpay.webpay.transbank.com/")]
    public partial class wsCompleteAuthorizeOutput {
        
        private string accountingDateField;
        
        private string buyOrderField;
        
        private wsTransactionDetailOutput[] detailsOutputField;
        
        private string sessionIdField;
        
        private System.DateTime transactionDateField;
        
        private bool transactionDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accountingDate {
            get {
                return this.accountingDateField;
            }
            set {
                this.accountingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string buyOrder {
            get {
                return this.buyOrderField;
            }
            set {
                this.buyOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detailsOutput", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public wsTransactionDetailOutput[] detailsOutput {
            get {
                return this.detailsOutputField;
            }
            set {
                this.detailsOutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime transactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionDateSpecified {
            get {
                return this.transactionDateFieldSpecified;
            }
            set {
                this.transactionDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void acknowledgeCompleteTransactionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void authorizeCompletedEventHandler(object sender, authorizeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authorizeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authorizeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsCompleteAuthorizeOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsCompleteAuthorizeOutput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void queryShareCompletedEventHandler(object sender, queryShareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryShareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryShareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsCompleteQuerySharesOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsCompleteQuerySharesOutput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void initCompleteTransactionCompletedEventHandler(object sender, initCompleteTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class initCompleteTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal initCompleteTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsCompleteInitTransactionOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsCompleteInitTransactionOutput)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591
