//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace Transbank.Webpay.Wsdl.OneClick.Certificacion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OneClickPaymentServiceImplServiceSoapBinding", Namespace="http://webservices.webpayserver.transbank.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseBean))]
    public partial class OneClickPaymentServiceImplService : Microsoft.Web.Services3.WebServicesClientProtocol
    {
        
        private System.Threading.SendOrPostCallback removeUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback initInscriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback finishInscriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback codeReverseOneClickOperationCompleted;
        
        private System.Threading.SendOrPostCallback authorizeOperationCompleted;
        
        private System.Threading.SendOrPostCallback reverseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OneClickPaymentServiceImplService() {
            this.Url = global::Transbank.Webpay.Properties.Settings.Default.Webpay_Transbank_Library_Wsdl_OneClick_Integracion_OneClickPaymentServiceImplService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event removeUserCompletedEventHandler removeUserCompleted;
        
        /// <remarks/>
        public event initInscriptionCompletedEventHandler initInscriptionCompleted;
        
        /// <remarks/>
        public event finishInscriptionCompletedEventHandler finishInscriptionCompleted;
        
        /// <remarks/>
        public event codeReverseOneClickCompletedEventHandler codeReverseOneClickCompleted;
        
        /// <remarks/>
        public event authorizeCompletedEventHandler authorizeCompleted;
        
        /// <remarks/>
        public event reverseCompletedEventHandler reverseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservices.webpayserver.transbank.com/", ResponseNamespace="http://webservices.webpayserver.transbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool removeUser([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] oneClickRemoveUserInput arg0) {
            object[] results = this.Invoke("removeUser", new object[] {
                        arg0});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void removeUserAsync(oneClickRemoveUserInput arg0) {
            this.removeUserAsync(arg0, null);
        }
        
        /// <remarks/>
        public void removeUserAsync(oneClickRemoveUserInput arg0, object userState) {
            if ((this.removeUserOperationCompleted == null)) {
                this.removeUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveUserOperationCompleted);
            }
            this.InvokeAsync("removeUser", new object[] {
                        arg0}, this.removeUserOperationCompleted, userState);
        }
        
        private void OnremoveUserOperationCompleted(object arg) {
            if ((this.removeUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeUserCompleted(this, new removeUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservices.webpayserver.transbank.com/", ResponseNamespace="http://webservices.webpayserver.transbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public oneClickInscriptionOutput initInscription([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] oneClickInscriptionInput arg0) {
            object[] results = this.Invoke("initInscription", new object[] {
                        arg0});
            return ((oneClickInscriptionOutput)(results[0]));
        }
        
        /// <remarks/>
        public void initInscriptionAsync(oneClickInscriptionInput arg0) {
            this.initInscriptionAsync(arg0, null);
        }
        
        /// <remarks/>
        public void initInscriptionAsync(oneClickInscriptionInput arg0, object userState) {
            if ((this.initInscriptionOperationCompleted == null)) {
                this.initInscriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OninitInscriptionOperationCompleted);
            }
            this.InvokeAsync("initInscription", new object[] {
                        arg0}, this.initInscriptionOperationCompleted, userState);
        }
        
        private void OninitInscriptionOperationCompleted(object arg) {
            if ((this.initInscriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.initInscriptionCompleted(this, new initInscriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservices.webpayserver.transbank.com/", ResponseNamespace="http://webservices.webpayserver.transbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public oneClickFinishInscriptionOutput finishInscription([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] oneClickFinishInscriptionInput arg0) {
            object[] results = this.Invoke("finishInscription", new object[] {
                        arg0});
            return ((oneClickFinishInscriptionOutput)(results[0]));
        }
        
        /// <remarks/>
        public void finishInscriptionAsync(oneClickFinishInscriptionInput arg0) {
            this.finishInscriptionAsync(arg0, null);
        }
        
        /// <remarks/>
        public void finishInscriptionAsync(oneClickFinishInscriptionInput arg0, object userState) {
            if ((this.finishInscriptionOperationCompleted == null)) {
                this.finishInscriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfinishInscriptionOperationCompleted);
            }
            this.InvokeAsync("finishInscription", new object[] {
                        arg0}, this.finishInscriptionOperationCompleted, userState);
        }
        
        private void OnfinishInscriptionOperationCompleted(object arg) {
            if ((this.finishInscriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.finishInscriptionCompleted(this, new finishInscriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservices.webpayserver.transbank.com/", ResponseNamespace="http://webservices.webpayserver.transbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public oneClickReverseOutput codeReverseOneClick([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] oneClickReverseInput arg0) {
            object[] results = this.Invoke("codeReverseOneClick", new object[] {
                        arg0});
            return ((oneClickReverseOutput)(results[0]));
        }
        
        /// <remarks/>
        public void codeReverseOneClickAsync(oneClickReverseInput arg0) {
            this.codeReverseOneClickAsync(arg0, null);
        }
        
        /// <remarks/>
        public void codeReverseOneClickAsync(oneClickReverseInput arg0, object userState) {
            if ((this.codeReverseOneClickOperationCompleted == null)) {
                this.codeReverseOneClickOperationCompleted = new System.Threading.SendOrPostCallback(this.OncodeReverseOneClickOperationCompleted);
            }
            this.InvokeAsync("codeReverseOneClick", new object[] {
                        arg0}, this.codeReverseOneClickOperationCompleted, userState);
        }
        
        private void OncodeReverseOneClickOperationCompleted(object arg) {
            if ((this.codeReverseOneClickCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.codeReverseOneClickCompleted(this, new codeReverseOneClickCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservices.webpayserver.transbank.com/", ResponseNamespace="http://webservices.webpayserver.transbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public oneClickPayOutput authorize([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] oneClickPayInput arg0) {
            object[] results = this.Invoke("authorize", new object[] {
                        arg0});
            return ((oneClickPayOutput)(results[0]));
        }
        
        /// <remarks/>
        public void authorizeAsync(oneClickPayInput arg0) {
            this.authorizeAsync(arg0, null);
        }
        
        /// <remarks/>
        public void authorizeAsync(oneClickPayInput arg0, object userState) {
            if ((this.authorizeOperationCompleted == null)) {
                this.authorizeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthorizeOperationCompleted);
            }
            this.InvokeAsync("authorize", new object[] {
                        arg0}, this.authorizeOperationCompleted, userState);
        }
        
        private void OnauthorizeOperationCompleted(object arg) {
            if ((this.authorizeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authorizeCompleted(this, new authorizeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservices.webpayserver.transbank.com/", ResponseNamespace="http://webservices.webpayserver.transbank.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool reverse([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] oneClickReverseInput arg0) {
            object[] results = this.Invoke("reverse", new object[] {
                        arg0});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void reverseAsync(oneClickReverseInput arg0) {
            this.reverseAsync(arg0, null);
        }
        
        /// <remarks/>
        public void reverseAsync(oneClickReverseInput arg0, object userState) {
            if ((this.reverseOperationCompleted == null)) {
                this.reverseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreverseOperationCompleted);
            }
            this.InvokeAsync("reverse", new object[] {
                        arg0}, this.reverseOperationCompleted, userState);
        }
        
        private void OnreverseOperationCompleted(object arg) {
            if ((this.reverseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reverseCompleted(this, new reverseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.webpayserver.transbank.com/")]
    public partial class oneClickRemoveUserInput : baseBean {
        
        private string tbkUserField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tbkUser {
            get {
                return this.tbkUserField;
            }
            set {
                this.tbkUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(oneClickPayOutput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(oneClickPayInput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(oneClickReverseOutput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(oneClickReverseInput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(oneClickFinishInscriptionOutput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(oneClickFinishInscriptionInput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(oneClickInscriptionOutput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(oneClickInscriptionInput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(oneClickRemoveUserInput))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.webpayserver.transbank.com/")]
    public partial class baseBean {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.webpayserver.transbank.com/")]
    public partial class oneClickPayOutput : baseBean {
        
        private string authorizationCodeField;
        
        private creditCardType creditCardTypeField;
        
        private bool creditCardTypeFieldSpecified;
        
        private string last4CardDigitsField;
        
        private int responseCodeField;
        
        private long transactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string authorizationCode {
            get {
                return this.authorizationCodeField;
            }
            set {
                this.authorizationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public creditCardType creditCardType {
            get {
                return this.creditCardTypeField;
            }
            set {
                this.creditCardTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creditCardTypeSpecified {
            get {
                return this.creditCardTypeFieldSpecified;
            }
            set {
                this.creditCardTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string last4CardDigits {
            get {
                return this.last4CardDigitsField;
            }
            set {
                this.last4CardDigitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.webpayserver.transbank.com/")]
    public enum creditCardType {
        
        /// <remarks/>
        Visa,
        
        /// <remarks/>
        AmericanExpress,
        
        /// <remarks/>
        MasterCard,
        
        /// <remarks/>
        Diners,
        
        /// <remarks/>
        Magna,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.webpayserver.transbank.com/")]
    public partial class oneClickPayInput : baseBean {
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private long buyOrderField;
        
        private bool buyOrderFieldSpecified;
        
        private string tbkUserField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long buyOrder {
            get {
                return this.buyOrderField;
            }
            set {
                this.buyOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool buyOrderSpecified {
            get {
                return this.buyOrderFieldSpecified;
            }
            set {
                this.buyOrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tbkUser {
            get {
                return this.tbkUserField;
            }
            set {
                this.tbkUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.webpayserver.transbank.com/")]
    public partial class oneClickReverseOutput : baseBean {
        
        private long reverseCodeField;
        
        private bool reverseCodeFieldSpecified;
        
        private bool reversedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long reverseCode {
            get {
                return this.reverseCodeField;
            }
            set {
                this.reverseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reverseCodeSpecified {
            get {
                return this.reverseCodeFieldSpecified;
            }
            set {
                this.reverseCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool reversed {
            get {
                return this.reversedField;
            }
            set {
                this.reversedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.webpayserver.transbank.com/")]
    public partial class oneClickReverseInput : baseBean {
        
        private long buyorderField;
        
        private bool buyorderFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long buyorder {
            get {
                return this.buyorderField;
            }
            set {
                this.buyorderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool buyorderSpecified {
            get {
                return this.buyorderFieldSpecified;
            }
            set {
                this.buyorderFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.webpayserver.transbank.com/")]
    public partial class oneClickFinishInscriptionOutput : baseBean {
        
        private string authCodeField;
        
        private creditCardType creditCardTypeField;
        
        private bool creditCardTypeFieldSpecified;
        
        private string last4CardDigitsField;
        
        private int responseCodeField;
        
        private string tbkUserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string authCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public creditCardType creditCardType {
            get {
                return this.creditCardTypeField;
            }
            set {
                this.creditCardTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creditCardTypeSpecified {
            get {
                return this.creditCardTypeFieldSpecified;
            }
            set {
                this.creditCardTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string last4CardDigits {
            get {
                return this.last4CardDigitsField;
            }
            set {
                this.last4CardDigitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tbkUser {
            get {
                return this.tbkUserField;
            }
            set {
                this.tbkUserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.webpayserver.transbank.com/")]
    public partial class oneClickFinishInscriptionInput : baseBean {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.webpayserver.transbank.com/")]
    public partial class oneClickInscriptionOutput : baseBean {
        
        private string tokenField;
        
        private string urlWebpayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string urlWebpay {
            get {
                return this.urlWebpayField;
            }
            set {
                this.urlWebpayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.webpayserver.transbank.com/")]
    public partial class oneClickInscriptionInput : baseBean {
        
        private string emailField;
        
        private string responseURLField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string responseURL {
            get {
                return this.responseURLField;
            }
            set {
                this.responseURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void removeUserCompletedEventHandler(object sender, removeUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class removeUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal removeUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void initInscriptionCompletedEventHandler(object sender, initInscriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class initInscriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal initInscriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public oneClickInscriptionOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((oneClickInscriptionOutput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void finishInscriptionCompletedEventHandler(object sender, finishInscriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class finishInscriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal finishInscriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public oneClickFinishInscriptionOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((oneClickFinishInscriptionOutput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void codeReverseOneClickCompletedEventHandler(object sender, codeReverseOneClickCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class codeReverseOneClickCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal codeReverseOneClickCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public oneClickReverseOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((oneClickReverseOutput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void authorizeCompletedEventHandler(object sender, authorizeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authorizeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authorizeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public oneClickPayOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((oneClickPayOutput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void reverseCompletedEventHandler(object sender, reverseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reverseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal reverseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591
