name: .NET CI

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Restore dependencies
        run: dotnet restore

      - name: Begin SonarCloud analysis
        run: dotnet sonarscanner begin /k:"TransbankDevelopers_transbank-sdk-dotnet" /o:"transbankdevelopers" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.opencover.reportsPaths="Tests/TestResults/**/coverage.opencover.xml" /d:sonar.scanner.scanAll=false

      - name: Build (required by SonarCloud)
        run: dotnet build --no-restore --configuration Release

      - name: Test with coverage
        run: dotnet test Tests/Tests.csproj --no-build --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=$(pwd)/Tests/TestResults/coverage.opencover.xml /p:CoverletOutputRelativePath=true
      
      - name: List coverage files
        run: ls -lR Tests/TestResults
      
      - name: End SonarCloud analysis
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: Tests/TestResults/**/coverage.opencover.xml
